# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'cloudtechmasters-dockerhub-connnection'
    repository: 'cloudtechmasters/dotnetcorewebapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'azure-acr-connection'
    repository: 'cloudtechmasters/dotnetcorewebapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
