on:
  push:
    branches:
      - main  # Set the branch where you want the action to trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Specify your .NET Core version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Build Docker image
      run: |
        docker build -t cloudtechmasters/dotnetcorewebapi:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push cloudtechmasters/dotnetcorewebapi:latest
